version: '3.8'

services:
  revalue-ai:
    build:
      context: .
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
    image: gcr.io/rivalueai/revalue-ai:latest
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - PORT=8080
    deploy:
      replicas: 1
